{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qmetry.fullname" . }}-secret
  labels: {{- include "qmetry.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  clickhouse-password: {{ .Values.secrets.clickHousePassword | quote }}
  oidc-client-secret: {{ .Values.secrets.oidcClientSecret | quote }}
  initial-admin-password: {{ .Values.secrets.initialAdminPassword | quote }}
{{- end -}}
