INSERT INTO products(name, category, price, stock) VALUES ('MacBook Pro 14',     'electronics', 1999.00, 25);
INSERT INTO products(name, category, price, stock) VALUES ('AirPods Pro',         'electronics',  249.00, 80);
INSERT INTO products(name, category, price, stock) VALUES ('LG 4K Monitor',       'electronics',  549.00, 12);
INSERT INTO products(name, category, price, stock) VALUES ('Magic Keyboard',      'electronics',  149.00, 40);
INSERT INTO products(name, category, price, stock) VALUES ('Logitech MX Mouse',   'electronics',   99.00, 60);
INSERT INTO products(name, category, price, stock) VALUES ('Sony WH-1000XM5',     'electronics',  399.00, 20);
INSERT INTO products(name, category, price, stock) VALUES ('iPad Air',            'electronics',  599.00, 35);
INSERT INTO products(name, category, price, stock) VALUES ('Effective Java 3rd',  'books',         42.00, 100);
INSERT INTO products(name, category, price, stock) VALUES ('Designing Data-Intensive Applications', 'books', 48.00, 50);
INSERT INTO products(name, category, price, stock) VALUES ('Clean Architecture',  'books',         35.00, 75);
INSERT INTO products(name, category, price, stock) VALUES ('Kindle Paperwhite',   'electronics',  139.00, 90);
INSERT INTO products(name, category, price, stock) VALUES ('Instant Pot',         'kitchen',       89.00, 30);
INSERT INTO products(name, category, price, stock) VALUES ('Nespresso Vertuo',    'kitchen',      199.00, 15);
INSERT INTO products(name, category, price, stock) VALUES ('Cast Iron Skillet',   'kitchen',       45.00, 50);
INSERT INTO products(name, category, price, stock) VALUES ('Stand Mixer',         'kitchen',      349.00, 10);
INSERT INTO products(name, category, price, stock) VALUES ('Bose Soundbar',       'electronics',  799.00, 18);
INSERT INTO products(name, category, price, stock) VALUES ('Mechanical Keyboard', 'electronics',  179.00, 22);
INSERT INTO products(name, category, price, stock) VALUES ('USB-C Hub',           'electronics',   59.00, 70);
INSERT INTO products(name, category, price, stock) VALUES ('Webcam HD',           'electronics',   79.00, 45);
INSERT INTO products(name, category, price, stock) VALUES ('Desk Lamp',           'kitchen',       29.00, 100);

INSERT INTO users(name, email) VALUES ('Alice Wonderland',   'alice@example.com');
INSERT INTO users(name, email) VALUES ('Bob the Builder',    'bob@example.com');
INSERT INTO users(name, email) VALUES ('Carol Singer',       'carol@example.com');
INSERT INTO users(name, email) VALUES ('David Copperfield',  'david@example.com');
INSERT INTO users(name, email) VALUES ('Eve Online',         'eve@example.com');
INSERT INTO users(name, email) VALUES ('Frank Underwood',    'frank@example.com');
INSERT INTO users(name, email) VALUES ('Grace Hopper',       'grace@example.com');
INSERT INTO users(name, email) VALUES ('Henry Ford',         'henry@example.com');
INSERT INTO users(name, email) VALUES ('Iris West',          'iris@example.com');
INSERT INTO users(name, email) VALUES ('Jack Sparrow',       'jack@example.com');
