package chstore

import (
	"fmt"
	"strings"
)

// FilterExpr is a single advanced filter clause: `key op value(s)`.
// `Key` may be a well-known column ("service.name", "http.method", …) or any
// custom attribute name — looked up in the attr_keys/attr_values arrays.
type FilterExpr struct {
	Key    string   `json:"k"`
	Op     string   `json:"op"`
	Values []string `json:"v"`
}

// Allowed operator set. Anything else is rejected at parse time.
var allowedOps = map[string]bool{
	"=": true, "!=": true,
	"LIKE": true, "NOT LIKE": true,
	"IN": true, "NOT IN": true,
	">": true, ">=": true, "<": true, "<=": true,
	"EXISTS": true, "NOT EXISTS": true,
}

// Map of well-known span attribute names to dedicated ClickHouse columns,
// so common queries skip the array lookup and stay index-friendly.
var wellKnown = map[string]string{
	"service.name":      "service_name",
	"service_name":      "service_name",
	"name":              "name",
	"operation":         "name",
	"kind":              "kind",
	"status_code":       "status_code",
	"status":            "status_code",
	"host.name":         "host_name",
	"deployment.environment": "deploy_env",
	"http.method":       "http_method",
	"http.route":        "http_route",
	"http.status_code":  "http_status",
	"db.system":         "db_system",
	"db.statement":      "db_statement",
	"rpc.system":        "rpc_system",
	"rpc.method":        "rpc_method",
	"peer.service":      "peer_service",
	"messaging.system":  "msg_system",
	"duration_ms":       "(duration / 1e6)",
	// v0.5.271 — added for DQL cross-signal join. The
	// FilterExpr{Key:"trace.id", Op:"IN", Values:[ids]} shape
	// generated by the join executor needs the dotted form to
	// resolve to the dedicated trace_id column.
	"trace.id":          "trace_id",
	"traceId":           "trace_id",
	"trace_id":          "trace_id",
	"span.id":           "span_id",
	"span_id":           "span_id",
}

// SQL builds the WHERE fragment + arg list for this filter, or returns
// (empty, nil, error) if the expression is malformed.
//
// For unknown attribute keys, the lookup expression `attr_values[indexOf(attr_keys, ?)]`
// pushes the key as a parameter. For numeric ops we cast to Float64 so that
// even string-stored attributes compare correctly when they parse.
func (f FilterExpr) SQL() (string, []any, error) {
	return f.sql("")
}

// SQLAliased is the alias-qualified twin of SQL: every column reference is
// prefixed with `<alias>.` so the fragment is safe to use inside a self-join
// over `spans AS <alias>` (relations.go, v0.8.x). With an empty alias it is
// byte-identical to SQL() — the existing flat-filter callers are unchanged.
//
// Only the alias is concatenated into the SQL text; it is validated by the
// caller (relations.go uses the fixed literals "c" / "p"), never threaded
// from user input. Keys and values still flow exclusively as `?` params.
func (f FilterExpr) SQLAliased(alias string) (string, []any, error) {
	return f.sql(alias)
}

// qualCol prefixes a well-known column expression (which may itself be a
// compound expression like "(duration / 1e6)") with the join alias. An empty
// alias is a no-op so SQL() stays byte-identical to its pre-alias form.
func qualCol(alias, col string) string {
	if alias == "" {
		return col
	}
	// Compound well-known expr — only `(duration / 1e6)` today. Qualify the
	// inner column rather than the whole parenthesised expression.
	if strings.HasPrefix(col, "(") {
		return strings.Replace(col, "duration", alias+".duration", 1)
	}
	return alias + "." + col
}

// qualArr prefixes the array-lookup columns (attr/res keys+values) with the
// join alias. arrCol is the bare expression, e.g.
// "attr_values[indexOf(attr_keys, ?)]" or "has(res_keys, ?)".
func qualArr(alias, expr string) string {
	if alias == "" {
		return expr
	}
	r := strings.NewReplacer(
		"attr_values", alias+".attr_values",
		"attr_keys", alias+".attr_keys",
		"res_values", alias+".res_values",
		"res_keys", alias+".res_keys",
	)
	return r.Replace(expr)
}

func (f FilterExpr) sql(alias string) (string, []any, error) {
	op := strings.ToUpper(strings.TrimSpace(f.Op))
	if op == "" {
		op = "="
	}
	if !allowedOps[op] {
		return "", nil, fmt.Errorf("invalid operator %q", op)
	}
	if f.Key == "" {
		return "", nil, fmt.Errorf("missing key")
	}

	// Resolve the LHS expression. Tempo-style prefixes pick the array:
	//   resource.X  →  res_values[indexOf(res_keys, 'X')]
	//   span.X      →  attr_values[indexOf(attr_keys, 'X')]
	//   X           →  well-known dedicated column if any, else span attr
	var lhs string
	var args []any
	switch {
	case strings.HasPrefix(f.Key, "resource."):
		name := strings.TrimPrefix(f.Key, "resource.")
		lhs = qualArr(alias, "res_values[indexOf(res_keys, ?)]")
		args = append(args, name)
	case strings.HasPrefix(f.Key, "span."):
		name := strings.TrimPrefix(f.Key, "span.")
		// Allow span.<known> to fall back to the dedicated column for indexing
		if col, ok := wellKnown[name]; ok {
			lhs = qualCol(alias, col)
		} else {
			lhs = qualArr(alias, "attr_values[indexOf(attr_keys, ?)]")
			args = append(args, name)
		}
	default:
		if col, ok := wellKnown[f.Key]; ok {
			lhs = qualCol(alias, col)
		} else {
			lhs = qualArr(alias, "attr_values[indexOf(attr_keys, ?)]")
			args = append(args, f.Key)
		}
	}

	// Numeric ops get a Float64 cast — `attr_values` is String, so this
	// turns "200" into 200.0 for comparison without breaking text columns.
	numericOp := op == ">" || op == ">=" || op == "<" || op == "<="

	switch op {
	case "EXISTS", "NOT EXISTS":
		neg := op == "NOT EXISTS"
		// Pick the right array (or use the dedicated column if well-known).
		var hasExpr string
		var hArgs []any
		switch {
		case strings.HasPrefix(f.Key, "resource."):
			name := strings.TrimPrefix(f.Key, "resource.")
			hasExpr = qualArr(alias, "has(res_keys, ?)"); hArgs = []any{name}
		case strings.HasPrefix(f.Key, "span."):
			name := strings.TrimPrefix(f.Key, "span.")
			if _, ok := wellKnown[name]; ok {
				hasExpr = "(" + qualCol(alias, wellKnown[name]) + " != '')"
			} else {
				hasExpr = qualArr(alias, "has(attr_keys, ?)"); hArgs = []any{name}
			}
		default:
			if _, ok := wellKnown[f.Key]; ok {
				hasExpr = "(" + qualCol(alias, wellKnown[f.Key]) + " != '')"
			} else {
				hasExpr = qualArr(alias, "has(attr_keys, ?)"); hArgs = []any{f.Key}
			}
		}
		if neg {
			hasExpr = "NOT " + hasExpr
		}
		return hasExpr, hArgs, nil

	case "IN", "NOT IN":
		if len(f.Values) == 0 {
			return "", nil, fmt.Errorf("op %s needs at least one value", op)
		}
		placeholders := strings.TrimRight(strings.Repeat("?,", len(f.Values)), ",")
		for _, v := range f.Values {
			args = append(args, v)
		}
		return lhs + " " + op + " (" + placeholders + ")", args, nil

	case "LIKE", "NOT LIKE":
		if len(f.Values) != 1 {
			return "", nil, fmt.Errorf("op %s needs exactly one value", op)
		}
		args = append(args, "%"+f.Values[0]+"%")
		return lhs + " " + op + " ?", args, nil

	default: // =, !=, comparison ops
		if len(f.Values) != 1 {
			return "", nil, fmt.Errorf("op %s needs exactly one value", op)
		}
		if numericOp {
			// Cast to Float64. accurateCastOrNull is type-tolerant and handles
			// both String (attribute lookups) and numeric (well-known) columns.
			args = append(args, f.Values[0])
			return "accurateCastOrNull(" + lhs + ", 'Float64') " + op +
				" accurateCastOrNull(?, 'Float64')", args, nil
		}
		args = append(args, f.Values[0])
		return lhs + " " + op + " ?", args, nil
	}
}

// ApplyFilters appends each filter as a separate WHERE conjunct, skipping
// (and logging) any that fail to compile.
func ApplyFilters(wc *whereClause, filters []FilterExpr) {
	for _, f := range filters {
		sql, args, err := f.SQL()
		if err != nil || sql == "" {
			continue // silently skip — UI validates first
		}
		wc.add(sql, args...)
	}
}

// FilterGroup is a grouped boolean combination of FilterExpr leaves and
// (one level of) nested groups, joined by a single AND/OR operator. It is
// the additive, default-off upgrade over the flat conjunction-only
// `[]FilterExpr` path: an operator can finally express
// `(http.status >= 500 OR db.system = oracle) AND env = prod`.
//
// Depth cap: v1 supports exactly ONE level of nested groups. The top-level
// group may carry Groups; nested groups carry only Filters (deeper Groups
// are ignored by BuildFilterGroupSQL). One level buys ~95% of real queries
// per the trace-query-explore spec; arbitrary nesting is a bigger UI + URL
// codec lift deferred past v1.
//
// BACK-COMPAT CONTRACT (pinned by filtergroup_test.go): a flat-AND group —
// `FilterGroup{Join:"AND", Filters:<legacy []FilterExpr>}` with no Groups —
// emits byte-identical SQL + args to the legacy ApplyFilters path, so saved
// views / shared URLs / DQL / facets are untouched. The flat-AND case is
// routed straight through ApplyFilters precisely so it cannot drift.
type FilterGroup struct {
	Join    string        `json:"join"`   // "AND" | "OR" (default AND)
	Filters []FilterExpr  `json:"filters"`
	Groups  []FilterGroup `json:"groups,omitempty"`
}

// isFlatAnd reports whether the group is equivalent to the legacy flat
// conjunction-only path: AND-joined leaves, no nested groups. Used both by
// ApplyFilterGroup (to take the byte-identical fast path) and by the
// repo-layer MV gate (an OR / nested group disqualifies the
// trace_summary_5m fast-path exactly like Search / custom-attr does today).
func (g FilterGroup) isFlatAnd() bool {
	if len(g.Groups) > 0 {
		return false
	}
	return joinOp(g.Join) == "AND"
}

// IsFlatAnd is the exported guard the repo MV gate calls on an optional
// *FilterGroup: a nil root or a flat-AND root keeps the MV fast-path; any
// OR / nested group falls to the raw-spans GROUP-BY path (same cost class
// as free-text Search today).
func (g *FilterGroup) IsFlatAnd() bool {
	if g == nil {
		return true
	}
	return g.isFlatAnd()
}

// hasPredicate reports whether the group would contribute ANY compilable
// WHERE term. nil-safe so the repo MV gate can call it on an optional
// *FilterGroup: a nil or empty root contributes nothing (MV fast-path
// stays eligible), any compilable leaf — flat-AND or OR — disqualifies the
// MV exactly like a legacy non-empty Filters slice does today.
func (g *FilterGroup) hasPredicate() bool {
	if g == nil {
		return false
	}
	sql, _ := BuildFilterGroupSQL(*g)
	return sql != ""
}

// joinOp normalises the join operator to "AND" or "OR"; anything unknown /
// empty defaults to "AND" (the safe, legacy-equivalent operator).
func joinOp(j string) string {
	if strings.EqualFold(strings.TrimSpace(j), "OR") {
		return "OR"
	}
	return "AND"
}

// buildGroupFragment renders a group to a single parenthesised SQL fragment
// + ordered args, reusing FilterExpr.SQL() per leaf. Malformed / empty
// leaves are silently skipped (mirrors ApplyFilters' contract). nested is
// true when rendering a child group (caps the depth at one level — a
// nested group's own Groups are ignored).
//
// Returns ("", nil) when the group yields no compilable terms, so the
// caller can omit it entirely.
func buildGroupFragment(g FilterGroup, nested bool) (string, []any) {
	op := joinOp(g.Join)
	var parts []string
	var args []any
	for _, f := range g.Filters {
		sql, fargs, err := f.SQL()
		if err != nil || sql == "" {
			continue // silently skip — UI validates first
		}
		parts = append(parts, sql)
		args = append(args, fargs...)
	}
	if !nested {
		for _, sub := range g.Groups {
			// Depth cap: render child groups as leaf fragments (their own
			// Groups are ignored — see the FilterGroup depth-cap doc).
			frag, fargs := buildGroupFragment(sub, true)
			if frag == "" {
				continue
			}
			parts = append(parts, frag)
			args = append(args, fargs...)
		}
	}
	if len(parts) == 0 {
		return "", nil
	}
	if len(parts) == 1 {
		// A single term needs no wrapping parens when it's already a
		// self-contained fragment; but a nested child is always wrapped so
		// the parent's join can't bind across it. Top-level single term
		// returns bare (matches the flat path's per-conjunct add).
		if nested {
			return "(" + parts[0] + ")", args
		}
		return parts[0], args
	}
	return "(" + strings.Join(parts, " "+op+" ") + ")", args
}

// BuildFilterGroupSQL renders a FilterGroup to a single WHERE fragment +
// ordered args, ready to AND onto the rest of a query's predicates. Returns
// ("", nil) for a group with no compilable terms.
//
// For a flat-AND group it produces the same per-leaf SQL the legacy path
// produces, joined by " AND " (no outer parens at the top level when there's
// a single combined fragment) — but callers that need byte-identical
// behaviour with ApplyFilters should use ApplyFilterGroup, which routes the
// flat-AND case straight through ApplyFilters.
func BuildFilterGroupSQL(g FilterGroup) (string, []any) {
	return buildGroupFragment(g, false)
}

// ApplyFilterGroup appends a FilterGroup's predicates onto a whereClause.
//
//   - Flat-AND (no OR, no nested groups): delegated VERBATIM to ApplyFilters
//     so the emitted conds + args are byte-identical to the legacy
//     `[]FilterExpr` path — each leaf is a separate ` AND `-joined conjunct.
//     This is the zero-risk back-compat path saved views ride on.
//   - Anything with OR or a nested group: rendered to a single parenthesised
//     fragment via BuildFilterGroupSQL and added as ONE conjunct, so the
//     group's internal boolean structure is preserved against the
//     surrounding (always-AND) time / service / error predicates.
func ApplyFilterGroup(wc *whereClause, g FilterGroup) {
	if g.isFlatAnd() {
		ApplyFilters(wc, g.Filters)
		return
	}
	sql, args := BuildFilterGroupSQL(g)
	if sql == "" {
		return
	}
	wc.add(sql, args...)
}
