apiVersion: v2
name: coremetry
description: Enterprise OpenTelemetry APM — traces, metrics, logs, profiles on ClickHouse
type: application
version: 0.8.1
appVersion: "0.8.171"
home: https://github.com/cilcenk/coremetry
keywords:
  - apm
  - opentelemetry
  - observability
  - tracing
  - clickhouse
  - openshift
annotations:
  category: Observability
  charts.openshift.io/name: Coremetry
  charts.openshift.io/provider: Coremetry
maintainers:
  - name: Coremetry Maintainers
    email: cil.cenk@gmail.com
sources:
  - https://github.com/cilcenk/coremetry
